{% set version = "2022.2.1" %}
{% set sha256sum = "1d9195b76d2ea25c2b5ae9bee52d05075244d78fcd9c58ee0b6fac47d395a5eb" %}

{% set reldate = "{:d}-{:02d}-{:02d}".format(*(version.split(".") | map("int"))) %}

package:
  name: ca-certificates
  version: {{ version }}

source:
  # updates and sha256 published at: https://curl.haxx.se/docs/caextract.html
  fn: cacert.pem
  url: https://curl.haxx.se/ca/cacert-{{ reldate }}.pem
  sha256: {{ sha256sum }}

build:
  number: 0

test:
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/conda-forge/ca-certificates-feedstock
  license: MPL-2.0
  license_file: LICENSE.txt
  summary: Certificates for use with other packages.
  doc_url: https://github.com/curl/curl/blob/master/docs/SSLCERTS.md

extra:
  recipe-maintainers:
     - jakirkham
     - jjhelmus
     - msarahan
     - mwcraig
     - ocefpaf
     - patricksnape
     - pelson
     - scopatz
