{% set version = "2021.10.26" %}
{% set sha256sum = "ae31ecb3c6e9ff3154cb7a55f017090448f88482f0e94ac927c0c67a1f33b9cf" %}

{% set reldate = "{:d}-{:02d}-{:02d}".format(*(version.split(".") | map("int"))) %}

package:
  name: ca-certificates
  version: {{ version }}

source:
  # updates and sha256 published at: https://curl.haxx.se/docs/caextract.html
  fn: cacert.pem
  url: https://curl.haxx.se/ca/cacert-{{ reldate }}.pem
  sha256: {{ sha256sum }}

build:
  number: 3

test:
  requires:
    - python <3.10
    - pip
  commands:
    - pip check

about:
  home: https://github.com/conda-forge/ca-certificates-feedstock
  license: MPL-2.0
  license_file: LICENSE.txt
  summary: Certificates for use with other packages.

extra:
  recipe-maintainers:
     - jakirkham
     - jjhelmus
     - msarahan
     - mwcraig
     - ocefpaf
     - patricksnape
     - pelson
     - scopatz
